app:
  name: luke-chu-site-api
  env: dev
  port: 8080

server:
  read_timeout: 10
  write_timeout: 15

postgres:
  host: 127.0.0.1
  port: 5432
  user: admin
  password: "1234"
  dbname: luke-chu-site
  sslmode: disable
  max_open_conns: 30
  max_idle_conns: 15
  conn_max_lifetime_minutes: 30

oss:
  bucket_name: luke-chu-site-photography
  endpoint: oss-cn-hongkong.aliyuncs.com
  public_base_url: https://luke-chu-site-photography.oss-cn-hongkong.aliyuncs.com
  region: cn-hongkong
  presign_expire_seconds: 300

security:
  behavior:
    enabled: true
    window_seconds: 60
    ip_limit_per_window: 120
    suspicious_ip_limit_per_window: 20

log:
  level: info
